package ie.gmit.sw.ai;

import java.util.Scanner;

public class Runner {
	
	PlayFair pf = new PlayFair();
	
	private static String kw = "THEQUICKBROWNFOX";
	private static String mes = "THEHOBBITCHAPTERIANUNEXPECTEDPARTYINAHOLEINTHEGROUNDTHERELIVEDAHOBBITNOTANASTYDIRTYWETHOLEFILLEDWITHTHEENDSOFWORMSANDANOOZYSMELLNORYETADRYBARESANDYHOLEWITHNOTHINGINITTOSITDOWNONORTOEATITWASAHOBBITHOLEANDTHATMEANSCOMFO\r\n" + 
			"RTITHADAPERFECTLYROUNDDOORLIKEAPORTHOLEPAINTEDGREENWITHASHINYYELLOWBRASSKNOBINTHEEXACTMIDDLETHEDOOROPENEDONTOATUBESHAPEDHALLLIKEATUNNELAVERYCOMFORTABLETUNNELWITHOUTSMOKEWITHPANELLEDWALLSANDFLOORSTILEDANDCARPETEDPROVIDEDWITHP\r\n" + 
			"OLISHEDCHAIRSANDLOTSANDLOTSOFPEGSFORHATSANDCOATSTHEHOBBITWASFONDOFVISITORSTHETUNNELWOUNDONANDONGOINGFAIRLYBUTNOTQUITESTRAIGHTINTOTHESIDEOFTHEHILLTHEHILLASALLTHEPEOPLEFORMANYMILESROUNDCALLEDITANDMANYLITTLEROUNDDOORSOPENEDOUTOFITF\r\n" + 
			"IRSTONONESIDEANDTHENONANOTHERNOGOINGUPSTAIRSFORTHEHOBBITBEDROOMSBATHROOMSCELLARSPANTRIESLOTSOFTHESEWARDROBESHEHADWHOLEROOMSDEVOTEDTOCLOTHESKITCHENSDININGROOMSALLWEREONTHESAMEFLOORANDINDEEDONTHESAMEPASSAGETHEBESTROOMSWEREALLONTHE\r\n" + 
			"LEFTHANDSIDEGOINGINFORTHESEWERETHEONLYONESTOHAVEWINDOWSDEEPSETROUNDWINDOWSLOOKINGOVERHISGARDENANDMEADOWSBEYONDSLOPINGDOWNTOTHERIVERTHISHOBBITWASAVERYWELLTODOHOBBITANDHISNAMEWASBAGGINSTHEBAGGINSESHADLIVEDINTHENEIGHBOURHOODOFTHEHILL\r\n" + 
			"FORTIMEOUTOFMINDANDPEOPLECONSIDEREDTHEMVERYRESPECTABLENOTONLYBECAUSEMOSTOFTHEMWERERICHBUTALSOBECAUSETHEYNEVERHADANYADVENTURESORDIDANYTHINGUNEXPECTEDYOUCOULDTELLWHATABAGGINSWOULDSAYONANYQUESTIONWITHOUTTHEBOTHEROFASKINGHIMTHISISASTO\r\n" + 
			"RYOFHOWABAGGINSHADANADVENTUREANDFOUNDHIMSELFDOINGANDSAYINGTHINGSALTOGETHERUNEXPECTEDHEMAYHAVELOSTTHENEIGHBOURSRESPECTBUTHEGAINEDWELLYOUWILLSEEWHETHERHEGAINEDANYTHINGINTHEENDTHEMOTHEROFOURPARTICULARHOBBITWHATISAHOBBITISUPPOSEHOBBIT\r\n" + 
			"SNEEDSOMEDESCRIPTIONNOWADAYSSINCETHEYHAVEBECOMERAREANDSHYOFTHEBIGPEOPLEASTHEYCALLUSTHEYAREORWEREALITTLEPEOPLEABOUTHALFOURHEIGHTANDSMALLERTHANTHEBEARDEDDWARVESHOBBITSHAVENOBEARDSTHEREISLITTLEORNOMAGICABOUTTHEMEXCEPTTHEORDINARYEVERYD\r\n" + 
			"AYSORTWHICHHELPSTHEMTODISAPPEARQUIETLYANDQUICKLYWHENLARGESTUPIDFOLKLIKEYOUANDMECOMEBLUNDERINGALONGMAKINGANOISELIKEELEPHANTSWHICHTHEYCANHEARAMILEOFFTHEYAREINCLINEDTOBEFATINTHESTOMACHTHEYDRESSINBRIGHTCOLOURSCHIEFLYGREENANDYELLOWWEARN\r\n" + 
			"OSHOESBECAUSETHEIRFEETGROWNATURALLEATHERYSOLESANDTHICKWARMBROWNHAIRLIKETHESTUFFONTHEIRHEADSWHICHISCURLYHAVELONGCLEVERBROWNFINGERSGOODNATUREDFACESANDLAUGHDEEPFRUITYLAUGHSESPECIALLYAFTERDINNERWHICHTHEYHAVETWICEADAYWHENTHEYCANGETITNOW\r\n" + 
			"YOUKNOWENOUGHTOGOONWITHASIWASSAYINGTHEMOTHEROFTHISHOBBITOFBILBOBAGGINSTHATISWASTHEFAMOUSBELLADONNATOOKONEOFTHETHREEREMARKABLEDAUGHTERSOFTHEOLDTOOKHEADOFTHEHOBBITSWHOLIVEDACROSSTHEWATERTHESMALLRIVERTHATRANATTHEFOOTOFTHEHILLITWASOFTE";

    public static void main(String[] args) {

    	PlayFair pf = new PlayFair();
        String key = pf.prompt("", kw, 6);
        String txt = pf.prompt("", mes, 1);
        String jti = pf.prompt("", kw, 1);
 
        boolean changeJtoI = jti.equalsIgnoreCase("y");
 
        pf.createTable(key, changeJtoI);
 
        String enc = pf.encode(pf.prepareText(txt, changeJtoI));
 
        System.out.printf("%nEncoded message: %n%s%n", enc);
        System.out.printf("%nDecoded message: %n%s%n", pf.decode(enc));
    }
}



