package ie.gmit.sw.ai;

import java.io.IOException;
import java.util.Scanner;

public class Runner {
	

	
	private static String kw = "thequickbrownfoxjumpedoverthelazydog";
	private static String mes = "THEHOBBITCHAPTERIANUNEXPECTEDPARTYINAHOLEINTHEGROUNDTHERELIVEDAHOBBITNOTANASTYDIRTYWETHOLEFILLEDWITHTHEENDSOFWORMSANDANOOZYSMELLNORYETADRYBARESANDYHOLEWITHNOTHINGINITTOSITDOWNONORTOEATITWASAHOBBITHOLEANDTHATMEANSCOMFO\r\n" + 
			"RTITHADAPERFECTLYROUNDDOORLIKEAPORTHOLEPAINTEDGREENWITHASHINYYELLOWBRASSKNOBINTHEEXACTMIDDLETHEDOOROPENEDONTOATUBESHAPEDHALLLIKEATUNNELAVERYCOMFORTABLETUNNELWITHOUTSMOKEWITHPANELLEDWALLSANDFLOORSTILEDANDCARPETEDPROVIDEDWITHP\r\n" + 
			"OLISHEDCHAIRSANDLOTSANDLOTSOFPEGSFORHATSANDCOATSTHEHOBBITWASFONDOFVISITORSTHETUNNELWOUNDONANDONGOINGFAIRLYBUTNOTQUITESTRAIGHTINTOTHESIDEOFTHEHILLTHEHILLASALLTHEPEOPLEFORMANYMILESROUNDCALLEDITANDMANYLITTLEROUNDDOORSOPENEDOUTOFITF\r\n" + 
			"IRSTONONESIDEANDTHENONANOTHERNOGOINGUPSTAIRSFORTHEHOBBITBEDROOMSBATHROOMSCELLARSPANTRIESLOTSOFTHESEWARDROBESHEHADWHOLEROOMSDEVOTEDTOCLOTHESKITCHENSDININGROOMSALLWEREONTHESAMEFLOORANDINDEEDONTHESAMEPASSAGETHEBESTROOMSWEREALLONTHE\r\n" + 
			"LEFTHANDSIDEGOINGINFORTHESEWERETHEONLYONESTOHAVEWINDOWSDEEPSETROUNDWINDOWSLOOKINGOVERHISGARDENANDMEADOWSBEYONDSLOPINGDOWNTOTHERIVERTHISHOBBITWASAVERYWELLTODOHOBBITANDHISNAMEWASBAGGINSTHEBAGGINSESHADLIVEDINTHENEIGHBOURHOODOFTHEHILL\r\n" + 
			"FORTIMEOUTOFMINDANDPEOPLECONSIDEREDTHEMVERYRESPECTABLENOTONLYBECAUSEMOSTOFTHEMWERERICHBUTALSOBECAUSETHEYNEVERHADANYADVENTURESORDIDANYTHINGUNEXPECTEDYOUCOULDTELLWHATABAGGINSWOULDSAYONANYQUESTIONWITHOUTTHEBOTHEROFASKINGHIMTHISISASTO\r\n" + 
			"RYOFHOWABAGGINSHADANADVENTUREANDFOUNDHIMSELFDOINGANDSAYINGTHINGSALTOGETHERUNEXPECTEDHEMAYHAVELOSTTHENEIGHBOURSRESPECTBUTHEGAINEDWELLYOUWILLSEEWHETHERHEGAINEDANYTHINGINTHEENDTHEMOTHEROFOURPARTICULARHOBBITWHATISAHOBBITISUPPOSEHOBBIT\r\n" + 
			"SNEEDSOMEDESCRIPTIONNOWADAYSSINCETHEYHAVEBECOMERAREANDSHYOFTHEBIGPEOPLEASTHEYCALLUSTHEYAREORWEREALITTLEPEOPLEABOUTHALFOURHEIGHTANDSMALLERTHANTHEBEARDEDDWARVESHOBBITSHAVENOBEARDSTHEREISLITTLEORNOMAGICABOUTTHEMEXCEPTTHEORDINARYEVERYD\r\n" + 
			"AYSORTWHICHHELPSTHEMTODISAPPEARQUIETLYANDQUICKLYWHENLARGESTUPIDFOLKLIKEYOUANDMECOMEBLUNDERINGALONGMAKINGANOISELIKEELEPHANTSWHICHTHEYCANHEARAMILEOFFTHEYAREINCLINEDTOBEFATINTHESTOMACHTHEYDRESSINBRIGHTCOLOURSCHIEFLYGREENANDYELLOWWEARN\r\n" + 
			"OSHOESBECAUSETHEIRFEETGROWNATURALLEATHERYSOLESANDTHICKWARMBROWNHAIRLIKETHESTUFFONTHEIRHEADSWHICHISCURLYHAVELONGCLEVERBROWNFINGERSGOODNATUREDFACESANDLAUGHDEEPFRUITYLAUGHSESPECIALLYAFTERDINNERWHICHTHEYHAVETWICEADAYWHENTHEYCANGETITNOW\r\n" + 
			"YOUKNOWENOUGHTOGOONWITHASIWASSAYINGTHEMOTHEROFTHISHOBBITOFBILBOBAGGINSTHATISWASTHEFAMOUSBELLADONNATOOKONEOFTHETHREEREMARKABLEDAUGHTERSOFTHEOLDTOOKHEADOFTHEHOBBITSWHOLIVEDACROSSTHEWATERTHESMALLRIVERTHATRANATTHEFOOTOFTHEHILLITWASOFTE";

    public static void main(String[] args) throws IOException {
    	
    	Grams g = new Grams();

    	PlayFair pf = new PlayFair();
    	Key k = new Key();
        String key = pf.prompt("", kw, 6);
        String txt = pf.prompt("", mes, 1);
        String jti = pf.prompt("", kw, 1);
        
        long startime = System.currentTimeMillis();
 
        boolean changeJtoI = jti.equalsIgnoreCase("y");
 
        pf.createTable(key, changeJtoI);
 
        String enc = pf.encode(pf.prepareText(txt, changeJtoI));
 
        System.out.printf("%nEncoded message: %n%s%n", enc);
        System.out.printf("%nDecoded message: %n%s%n", pf.decode(enc));
        
        
        //printing the fourgrams
        g.fourGrams();
        
        //Time
        long finishTime = System.currentTimeMillis() - startime;
        
        System.out.println("\nTIME: "+ finishTime+"ms");
        
        //Key Shuffle
        String GenKey = k.KeyGen();
        System.out.println(GenKey);
        
      
        
    }
}



